version: "3.8"
services:
  master:
    image: jkaninda/laravel-php-fpm
    container_name: php-fpm
    restart: unless-stopped     
    volumes:
      #Project root
      - ./:/var/www/html
    networks:
      - default #if you're using networks between containers
    environment:
      # inject on secret...
      - DB_HOST=
      - DB_PORT=
      - DB_DATABASE=
      - DB_USERNAME=
      - DB_PASSWORD=
    volumes:
      - /home/jefripunza/belajar-laravel-11/sqlite:/var/www/html/database/sqlite/database.sqlite

  #Nginx server
  nginx-server:
    image: jkaninda/nginx-fpm:alpine
    container_name: nginx-server
    restart: unless-stopped
    ports:
      - 3001:80
    volumes:
      - ./:/var/www/html
    environment:
      - DOCUMENT_ROOT=/var/www/html/public
      - CLIENT_MAX_BODY_SIZE=20M
      - PHP_FPM_HOST=php-fpm:9000 
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"