version: "3.8"
services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:80"
    environment:
      # inject on secret...
      # - DB_HOST=
      # - DB_PORT=
      # - DB_DATABASE=
      # - DB_USERNAME=
      # - DB_PASSWORD=
    network_mode: bridge
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /home/jefripunza/belajar-laravel-11/sqlite:/var/www/html/database/sqlite/database.sqlite
